name: flutter_local_authentication
description: A flutter plugin that allows access to Local Authentication / Biometrics on iOS, macOS, Linux and Android.
version: 0.0.3
homepage: https://github.com/eaceto/flutter_local_authentication
repository: https://github.com/eaceto/flutter_local_authentication

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_local_authentication
        pluginClass: FlutterLocalAuthenticationPlugin
      ios:
        pluginClass: FlutterLocalAuthenticationPlugin
      linux:
        pluginClass: FlutterLocalAuthenticationPlugin
      macos:
        pluginClass: FlutterLocalAuthenticationPlugin
